version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: uncanada_app
    container_name: uncanada_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: uncanada_webserver
    restart: unless-stopped
    ports:
      - "8021:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
